#!/usr/bin/env bash
# Generates one `<palette>-key` extension per file in _extensions/keynote/palettes/,
# so decks can use `format: <palette>-key-revealjs` without a theme path.
#
# To add a theme: create _extensions/keynote/palettes/<name>.scss (with a
# `// title: ...` comment), then run ./generate-themes.sh.
# Bump the version in _extensions/keynote/_extension.yml before a release;
# the generated themes take the same version.

set -euo pipefail
cd "$(dirname "$0")/_extensions"

version=$(sed -n 's/^version: *//p' keynote/_extension.yml)

# Remove previously generated themes so deleted palettes don't linger.
for yml in *-key/_extension.yml; do
  [ -e "$yml" ] || continue
  if head -1 "$yml" | grep -q '^# Generated by generate-themes.sh'; then
    rm -r "$(dirname "$yml")"
  fi
done

for palette in keynote/palettes/*.scss; do
  name=$(basename "$palette" .scss)
  title=$(sed -n 's|^// title: *||p' "$palette" | head -1)
  mkdir -p "$name-key"
  cat > "$name-key/_extension.yml" <<EOF
# Generated by generate-themes.sh from keynote/palettes/$name.scss. Do not edit.
title: ${title:-$name}
author: Pascal Burkhard
version: $version
quarto-required: ">=1.4.0"
contributes:
  formats:
    revealjs:
      theme: ["../keynote/global.scss", "../keynote/letterbox.scss", "../keynote/custom-callouts.scss", "../keynote/infographic.scss", "../keynote/palettes/$name.scss"]
      include-after-body: "../keynote/theme.html"
      filters:
        - ../keynote/custom-callouts.lua
      revealjs-plugins:
        - ../keynote/codewindow
      width: 1280
      height: 720
source: nenuial/quarto-keynote
EOF
  echo "$name-key"
done
